/* 
 * 
 * Task code generated by SAS® Studio 5.1
 * 
 * Generated on '4/26/18, 1:40 PM'
 * Generated by 'stpola'
 * Generated on server 'vdmmlwx6-mon'
 * Generated on SAS version 'V.03.04M0P041918'
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36'
 * Generated on web client 'http://vdmmlwx6-mon.uda.sashq-r.openstack.sas.com/SASStudioV/main?locale=en_US&launchedFromAppSwitcher=true'
 */

data casuser.newball;
	set CASUSER.CASBALL;
	CrAvg=CrHits/CrAtBat;
	CrAvg=ROUND(CrAvg,0.001);
run;